name: "store"

services:
  database:
    image: postgres:14.8-alpine3.18
    container_name: database
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
    volumes:
      - .\data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - database-api-bridge
  
  seq:
    image: datalust/seq:2024.3
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8020:80
      - 5341:5341
    volumes:
      - .\data:/var/lib/seq/data
  
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
    networks:
      - minio-api-bridge
  
  api:
    image: web
    container_name: api
    build:
      context: .
      dockerfile: Web/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DATABASE_CONNECTION: "Host=localhost;Port=5432;Database=postgres;SearchPath=public;Username=postgres;Password=123456",
      MINIO_OPTIONS__ACCESS_KEY: "store",
      MINIO_OPTIONS__SECRET_KEY: "TYIkGFpnFTReu9wZzOtJ3Bh6JFiDRqSKfqyxSvkM",
      MINIO_OPTIONS__ENDPOINT: "127.0.0.1:9000"
    ports:
      - "7171:8080"
    depends_on:
      - database
      - seq
      - minio
    networks:
      - database-api-bridge
      - minio-api-bridge


networks:
  minio-api-bridge:
    driver: bridge
  database-api-bridge:
    driver: bridge